# Generated by Django 3.1.7 on 2021-04-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_techtool_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techtool',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='techtool',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
