# Generated by Django 3.1.7 on 2021-04-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210417_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(default='img/undraw_profile.svg', upload_to='img/'),
        ),
    ]
