# Generated by Django 3.1.7 on 2021-04-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210417_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsissue',
            name='timeOut',
            field=models.BooleanField(default=False),
        ),
    ]
