# Generated by Django 3.1.7 on 2021-04-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_toolsissue_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsissue',
            name='borrowTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
