# Generated by Django 3.1.7 on 2021-04-14 14:07

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('1', ' team leader'), ('2', ' senior developer'), ('3', ' junior developer'), ('4', ' trainee developer')], max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('mobile', phone_field.models.PhoneField(blank=True, help_text='Contact mobile number', max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TechTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowTime', models.DateTimeField(auto_now_add=True)),
                ('SubmitDate', models.DateTimeField()),
                ('empName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
                ('techTool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.techtool')),
            ],
        ),
    ]
