# Generated by Django 3.1.7 on 2021-04-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210414_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('1', ' team leader'), ('2', ' senior developer'), ('3', ' junior developer'), ('4', ' trainee developer')], max_length=100),
        ),
    ]
