# Generated by Django 3.1.7 on 2021-04-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210414_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techtool',
            name='quantity',
        ),
    ]
