# Generated by Django 3.1.7 on 2021-04-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210416_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolsissue',
            old_name='SubmitDate',
            new_name='submitDate',
        ),
    ]
